# Generated by Django 2.2.7 on 2019-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191119_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
