# Generated by Django 2.2.7 on 2019-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('TU', 'Top up'), ('PU', 'Purchase food or drink')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
